### ISSUE TITLE
Revoir l'impression

### ISSUE THREAD

**Issue by Azurency** [Azurency/gari#55]
Ne pas imprimer les indisponibilité avec l'affectation, si la DT souhaite imprimer les indisponibilités, aller dans l'onglet correspondant.

**Idées** 

- Ajouter un menu dropdown qui propose `imprimer affectation`, `imprimer affectation et réserve` ou `imprimer réserve`.

**Comment by Azurency** [comment]
Avec le nouveau design, des pages blanches en trop ont refait leur apparition sur IE

**Comment by Azurency** [comment]
Toujours une page en trop d'imprimé
```css
html, body {
  border: 1px solid white;
  height: 99%;
  page-break-after: avoid;
  page-break-before: avoid;
}
```
